"""
Generates a downloadable PDF clinical co-pilot report, satisfying the
"Generate a downloadable PDF or DOCX report" mandatory requirement.
Includes: patient info, all model predictions + confidence, explainability
notes, text-triage summary, and the Human-in-the-Loop decision/audit trail.
"""

import io
import os
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
)


def generate_report(
    patient_id,
    xray_result=None,
    xray_image_path=None,
    heart_result=None,
    shap_pairs=None,
    text_summary=None,
    hitl_decision=None,
    hitl_notes=None,
    reviewer_name=None,
    output_path=None,
):
    if output_path is None:
        output_path = os.path.join(tempfile.gettempdir(), "copilot_report.pdf")

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=18)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=12)
    normal = styles["Normal"]

    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    story = []

    story.append(Paragraph("AI Healthcare Co-Pilot -- Clinical Decision Support Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Patient ID: {patient_id}", normal))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("1. Imaging Analysis (CNN + Grad-CAM)", h2))
    if xray_result:
        img_table_data = [
            ["Prediction", xray_result["label"]],
            ["Confidence", f"{xray_result['confidence']*100:.1f}%"],
        ]
        t = Table(img_table_data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ]))
        story.append(t)
        if xray_image_path:
            story.append(Spacer(1, 0.1 * inch))
            story.append(RLImage(xray_image_path, width=2.5 * inch, height=2.5 * inch))
            story.append(Paragraph("Grad-CAM overlay: warmer regions influenced the prediction most.", normal))
    else:
        story.append(Paragraph("No imaging data provided.", normal))

    story.append(Paragraph("2. Cardiac Risk Analysis (Tabular ANN + SHAP)", h2))
    if heart_result:
        t2 = Table([
            ["Prediction", heart_result["label"]],
            ["Confidence", f"{heart_result['confidence']*100:.1f}%"],
        ], colWidths=[150, 300])
        t2.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ]))
        story.append(t2)
        if shap_pairs:
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph("Top contributing features (SHAP):", normal))
            shap_data = [["Feature", "SHAP Impact"]] + [
                [f, f"{v:+.3f}"] for f, v in shap_pairs[:6]
            ]
            t3 = Table(shap_data, colWidths=[200, 150])
            t3.setStyle(TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ]))
            story.append(t3)
    else:
        story.append(Paragraph("No tabular data provided.", normal))

    story.append(Paragraph("3. Patient Note Analysis (Text/NLP)", h2))
    story.append(Paragraph(text_summary or "No free-text note provided.", normal))

    story.append(Paragraph("4. Human-in-the-Loop Review", h2))
    story.append(Paragraph(f"Reviewer: {reviewer_name or 'N/A'}", normal))
    story.append(Paragraph(f"Decision: {hitl_decision or 'Pending'}", normal))
    story.append(Paragraph(f"Reviewer notes: {hitl_notes or 'None'}", normal))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        "Disclaimer: This report is generated by an AI decision-support tool and "
        "is not a substitute for professional medical diagnosis. All recommendations "
        "require clinician review and approval.", normal))

    doc.build(story)
    return output_path
